name: Actualizar Datos
on:
  schedule:
    - cron: '0 0 * * *' # Esto significa: corre todos los días a las 00:00 UTC
  workflow_dispatch: # Esto nos permite probarlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Actualizar
        run: |
          # Aquí el robot "finge" una actualización. 
          # En el futuro, aquí pondrás un comando para consultar una API.
          echo '{"total": 44000000, "yesterday": 20000}' > stats.json
          
          git config user.name "MiRobot"
          git config user.email "robot@email.com"
          git add stats.json
          git commit -m "Actualizacion automatica"
          git push
